# Lab 0: Numpy on CPU v.s. Tensor on GPU

- Complete the following tasks
- Save and submit your Jupytor notebook

## Numpy on CPU
- Randomly generate the 3D coordinates of N=200 points (i.e., a Nx3 matrix) with Numpy
- Calculate the pairwise distnace (i.e., a NxN matrix) between the generated N points using for loops
- Calculate the pairwise distnace (i.e., a NxN matrix) between the generated N points using array broadcasting

In [1]:
# Randomly generate the 3D coordinates of N=200 points (i.e., a Nx3 matrix) with Numpy

import numpy as np

N = 200
coord = np.random.rand(N, 3)
print(coord[:5])

[[0.61865045 0.62448219 0.06845128]
 [0.54345478 0.5536324  0.26413391]
 [0.86490051 0.57572793 0.55436658]
 [0.14437755 0.15662917 0.33124073]
 [0.32667043 0.12132504 0.28861681]]


In [3]:
# Calculate the pairwise distnace (i.e., a NxN matrix) between the generated N points using for loops

def loop(coord):
    # add your codes here
    distance=np.empty([N,N])
    for i in range(N):
        for j in range(N):
            distance[i][j]=np.sqrt(np.sum((coord[i]-coord[j])**2))
    return distance
%timeit loop(coord)

182 ms ± 39 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
# Calculate the pairwise distnace (i.e., a NxN matrix) between the generated N points using array broadcasting

def broadcast(coord):
    # add your codes here
    distance=np.sqrt(np.sum((coord[np.newaxis,:,:]-coord[:,np.newaxis,:])**2,axis=-1))
    return distance
%timeit broadcast(coord)

1.05 ms ± 1.48 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## Tensor on GPU
- Repeat the above steps with PyTorch (instead of Numpy) on a GPU (instead of CPU)

In [5]:
# Randomly generate the 3D coordinates of N=200 points (i.e., a Nx3 matrix) with PyTorch

import random
import torch as pt

dev = random.randint(0, pt.cuda.device_count()-1)
pt.cuda.set_device(dev)
print('#device:', dev)

N = 200
coord = pt.rand(N, 3)
print(coord[:5])

#device: 4
tensor([[0.4729, 0.9713, 0.6328],
        [0.5109, 0.6798, 0.1906],
        [0.7616, 0.0803, 0.0258],
        [0.6367, 0.1036, 0.0338],
        [0.9235, 0.6887, 0.7858]])


In [6]:
# Calculate the pairwise distnace (i.e., a NxN matrix) between the generated N points using for loops

def loop(coord):
    # add your codes here
    distance=pt.empty([N,N])
    for i in range(N):
        for j in range(N):
            distance[i][j]=pt.sqrt(pt.sum((coord[i]-coord[j])**2))
    return distance
%timeit loop(coord)

889 ms ± 2.25 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
# Calculate the pairwise distnace (i.e., a NxN matrix) between the generated N points using array broadcasting

def broadcast(coord):
    # add your codes here
    distance=pt.sqrt(pt.sum((coord[None,:,:]-coord[:,None,:])**2,dim=-1))
    return distance
%timeit broadcast(coord)

343 µs ± 14.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


# Question

- Compare the running time of the above two approaches with different values of N
- Describe your key observation, and explain why it happened

Add your answers here


广播机制要优于传统的循环